---
- name: Deploy Nginx on Red Hat-based host
  hosts: rocky
  become: true
  vars:
    nginx_document_root: /usr/share/nginx/html
    nginx_listen_port: 80

  tasks:
    - name: Update all system packages to the latest version
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Install EPEL Repo
      ansible.builtin.dnf:
        name: epel-release
        state: present

    - name: Install Nginx
      ansible.builtin.dnf:
        name: nginx
        state: present
        update_cache: true

    - name: Create document root
      ansible.builtin.file:
        path: "{{ nginx_document_root }}"
        state: directory
        mode: "0755"

    - name: Apply Nginx config
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: "0644"
      notify: Reload Nginx

    - name: Copy website content
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: "{{ nginx_document_root }}/index.html"
        mode: "0644"

  handlers:
    - name: Reload Nginx
      ansible.builtin.systemd:
        name: nginx
        state: reloaded

