---
- name: Deploy Nginx on Ubuntu host
  hosts: main
  become: true
  vars:
    nginx_document_root: /usr/share/nginx/html
    nginx_listen_port: 80

  tasks:
    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true

    - name: Create document root
      ansible.builtin.file:
        path: "{{ nginx_document_root }}"
        state: directory
        mode: "0755"

    - name: Apply Nginx config
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: "0644"
      notify: Reload Nginx

    - name: Copy website content
      template:
        src: templates/index.html.j2
        dest: "{{ nginx_document_root }}/index.html"
        mode: "0644"

  handlers:
    - name: Reload Nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
